### ISSUE TITLE
Missing Texture 

### ISSUE THREAD

**Issue by ArceusComplex** [clumsyc/decoration-mod#4] opened 2023-11-22 03:02 UTC
![Screenshot_282](https://github.com/clumsyc/decoration-mod/assets/151701475/89a13878-99a1-477d-93f6-312d37a88230)
The Shower Enclosure for Furniture Expanded [FABRIC] is missing it's texture. We are using furnitureexpanded-1.1-1.19.2-Fabric.

**Comment by clumsyc** [comment] 2023-11-23 00:19
That's weird... everything is working perfectly fine on my tests.
Could you try disabling your shaders and custom textures (if using one) to see if that is the cause of the problem? you could also try re-downloading the mod, maybe something broke along the way.

**Comment by ArceusComplex** [comment] 2023-12-03 16:08
Sorry for the long awaited response I have been a bit busy. I have disabled the shaders that was being used but nothing different occurred. I will try a fresh installation of the mod to see if that changes anything. If it helps at all we are running a cobblemon server on 1.19.2 right now and have a custom resource pack for the custom models and sprites on the server. Not sure if that would be affecting the missing textures that we are getting on the server or not.

**Comment by clumsyc** [comment] 2023-12-07 01:10
I mean, you could try disabling all your resource packs, but unless they're _somehow_ removing or breaking the vanilla textures, it _shouldn't_ matter.
Anyways, try redownloading the mod. 
If the problem persists, you can test the mod alone (keep Fabric API installed).
- If it works fine, try installing back half the mods you had, keep going until you find the one causing problems. 
- Otherwise, if it doesn't work even when the mod is alone, please post your log.

Also, is the problem only happening with the shower enclosure?

**Comment by otterminator** [comment] 2023-12-24 21:54
This seems like it might be related to this, but I'm in the process of trying to troubleshoot an unrelated crash and while I was scrolling through the latest.log file I noticed the line _"Unable to load model: 'furnitureexpanded:block/shower_box_top' referenced from: furnitureexpanded:shower_box#facing=north,half=upper: java.lang.IllegalStateException: Model loader 'forge:multi-layer' not found. Registered loaders: forge:obj, forge:composite, forge:item-layers, forge:bucket, minecraft:elements"_ (log file here: https://mclo.gs/5jLGiUK (It shows up twice, because I think the game tried to recover and reload into the main menu a second time before it crashed)

Along with all the other stuff going wrong I thought I may have accidentally downloaded a forge version of this mod, so I double checked, and I had version 1.0.2-1.18.2-FABRIC in my mod folder, so I'm not sure what went wrong.

I don't really know for sure whether or not that's a normal message from the mod, and that's the only warning from it I saw (So I don't think it's related to the crash or anything game breaking), or whether or not that's something a mod conflict can cause (?), but after I checked to make sure I didn't have a forge version of this mod I checked the issue tracker here to see if maybe this was something someone else had happen/noticed, and saw this about the shower being broken. 

If it'd help for me to create a new issue I can. This with the missing textures has been something I noticed as well (I can remember before I tried to update all my mods having issues with missing textures on at least one of the items from this mod, I think it was visible from the creative menu (I'm pretty sure it was the shower but my memory's pretty bad so I'm not 100% sure))

**Comment by clumsyc** [comment] 2023-12-26 23:04
Hello @otterminator, thanks for pointing it out. 
This has been fixed on the 1.1 update (which is only available for 1.19+), it happened because all the new things added were ported from Forge and I forgot to update the showerbox model on fabric, so it won't show up properly (purple and black squares) and warn about how it couldn't load. Weirdly enough, it was working fine when I tested.

Anyways, I have hopefully fixed the issue, if you'd like to test (don't forget to unzip). If it's working I'll update the file on curseforge.
[furnitureexpanded-1.0.2-1.18.2-FABRIC.zip](https://github.com/clumsyc/decoration-mod/files/13774008/furnitureexpanded-1.0.2-1.18.2-FABRIC.zip)
If it doesn't work and you wish to receive further support, please submit a new issue.


And lastly, I'll wait a few more weeks. If OP doesn't reply, I'll consider this issue as solved. 
Just the game log is fine.

**Comment by LeonovAndre** [comment] 2024-01-25 14:39
I'm also having this issue:

![2024-01-25_11 23 18](https://github.com/clumsyc/decoration-mod/assets/140191230/f92de41e-20d5-432b-8be0-77ff2b13c802)


I'm running the mod on Fabric 1.19.2, mod version is 1.1-1.19.2. From experimentation it seems to be a problem with Create Fabric, which is also up-to-date. Here's the log: https://mclo.gs/cTTcXT1 It seems to work fine if I run it with the latest Create Forge version, but then other issues start to arise, like being unable to run create addons, and I'd prefer not to have to choose between Furniture Expanded and the create addons. Let me know if you need any other info :)

**Comment by clumsyc** [comment] 2024-01-26 00:10
@LeonovAndre Found the problem, thanks. 

For now, could you try this resourcepack? it should fix the issue.
1.19.2 only
[furnitureexpanded-1.19.2-texture-fix.zip](https://github.com/clumsyc/decoration-mod/files/14058717/furnitureexpanded-1.19.2-texture-fix.zip)

I don't know if this is happening in 1.19.4+ as well, but just in case this one should do for 1.19.4 ~ 1.20.x (even if it says it's not compatible)
[furnitureexpanded-1.19.4+-texture-fix.zip](https://github.com/clumsyc/decoration-mod/files/14058720/furnitureexpanded-1.19.4%2B-texture-fix.zip)

**Comment by LeonovAndre** [comment] 2024-01-27 15:20
The resourcepack works like a charm :) Thank you for the help and thank you for making such a fantastic mod ^^

**Comment by clumsyc** [comment] 2024-01-28 04:36
As I'm pretty sure this also solves the OP's issue, i'll be marking this as solved.
I'll be fixing this in the next release, so for the time being, please use the resourcepack.

**Closed as completed by clumsyc** 2024-01-28 04:36 UTC
